timeline
    title 허용 오차범위(Allowed Discrepancy) = 2
    section 유효하지 않음
    Period1 (30s) : 019235
    Period2 (60s) : 322675

    section 허용(과거)
    Period3 (90s) : 787652
    Period4 (120s): 105728

    section 현재
    Period5 (150s): 908012

    section 허용(미래)
    Period6 (180s): 337124
    Period7 (210s): 413290
